acronyms = {
    "AA":"Automobile Association / Activity Analysis / Alcoholics Anonymous",
    "AAIB":"Air Accident Investigation Branch",
    "ABC":"Activity Based Costing / Acceptable Behaviour Contract",
    "ABH":"Actual Bodily Harm",
    "ABI":"Association of British Insurers",
    "AC":"Alternating Current",
    "ACD":"Application for Communications Data / Automatic Call Distribution",
    "ACCOLC":"Access Overload Control",
    "ACC":"Assistant Chief Constable",
    "ACE CARD":"Approach from rear, Caution signs & cones, Examine the scene, Casualties, Ambulance e.t.c., Remove obstructions, Detailed Investigation (RTC Actions Mnemonic)",
    "ACIST":"ACPO Change and Implementation Support Team",
    "ACPC":"Area Child Protection Committee (Obsolete - now LSCB)",
    "ACPO":"Association of Chief Police Officers",
    "ACS":"Access Control System",
    "ACU":"Area Crime Unit",
    "ACW":"Anticlockwise",
    "ADAS":"Agricultural Development and Advisory Service",
    "ADP":"Automatic Data Processing",
    "ADR":"European Agreement Concerning the International Carriage of Dangerous Goods by Road",
    "ADHD":"Attention Deficit Hyperactivity Disorder",
    "ADS":"Accredited Document Set",
    "ADVOKATE":"Amount of time, Distance, Visibility, Obstructions, Known, Any reason to remember, Time lapsed, Errors (Mnemonic for eyewitness accutracy - 'Turnbull ruling')",
    "A&E":"Accident and Emergency",
    "AEA":"Approved Enforcement Agency",
    "AEAC":"Atomic Energy Authority Constabulary",
    "AFO":"Authorised Firearms Officer",
    "AFP":"Association of Forensic Physicians",
    "AFR":"Automatic Fingerprint Recognition",
    "AGR":"Advanced Gas-Cooled Reactor",
    "AHMP":"Authorised Mental Health Practitioner",
    "AIDS":"Acquired Immune Deficiency Syndrome",
    "AIS":"Military Aeronautical Information Service",
    "AIU":"Accident Investigation Unit",
    "AJD":"Administration of Justice Department (now Criminal Justice Department)",
    "AK":"Avtomat Kalashnikova ('Автома́т Кала́шникова', a Russian Kalashnikov Assault Rifle)",
    "":"",
}